//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasgemPortfolio.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CasgemPortfolioDbEntities : DbContext
    {
        public CasgemPortfolioDbEntities()
            : base("name=CasgemPortfolioDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TblFeature> TblFeature { get; set; }
        public DbSet<TblMessage> TblMessage { get; set; }
        public DbSet<TblService> TblService { get; set; }
        public DbSet<TblReference> TblReference { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TblDepartment> TblDepartment { get; set; }
        public DbSet<TblEmployee> TblEmployee { get; set; }
        public DbSet<TblResume> TblResume { get; set; }
        public DbSet<TblSkill> TblSkill { get; set; }
        public DbSet<TblWhoAmI> TblWhoAmI { get; set; }
        public DbSet<TblTestimonial> TblTestimonial { get; set; }
        public DbSet<TblProject> TblProject { get; set; }
    }
}
